/**
 * generated by Xtext 2.9.0
 */
package com.wso2.esb.dsl.scoping;

import com.wso2.esb.dsl.scoping.AbstractEsbDslScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class EsbDslScopeProvider extends AbstractEsbDslScopeProvider {
}
