/*
 * generated by Xtext 2.9.0
 */
package com.wso2.esb.dsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractEsbDslScopeProvider extends DelegatingScopeProvider {
}
