/**
 * generated by Xtext 2.9.0
 */
package com.wso2.esb.dsl.ui;

import com.wso2.esb.dsl.ui.AbstractEsbDslUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class EsbDslUiModule extends AbstractEsbDslUiModule {
  public EsbDslUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
