/*
 * generated by Xtext 2.9.0
 */
package com.wso2.esb.dsl.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractEsbDslValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(com.wso2.esb.dsl.esbDsl.EsbDslPackage.eINSTANCE);
		return result;
	}
	
}
