/**
 * generated by Xtext 2.9.0
 */
package com.wso2.esb.dsl.ui.contentassist;

import com.wso2.esb.dsl.ui.contentassist.AbstractEsbDslProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class EsbDslProposalProvider extends AbstractEsbDslProposalProvider {
}
