/**
 * generated by Xtext 2.9.0
 */
package com.wso2.esb.dsl.validation;

import com.wso2.esb.dsl.validation.AbstractEsbDslValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class EsbDslValidator extends AbstractEsbDslValidator {
}
