/**
 * generated by Xtext 2.9.0
 */
package com.wso2.esb.dsl.ui.labeling;

import com.google.inject.Inject;
import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider;

/**
 * Provides labels for EObjects.
 * 
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#label-provider
 */
@SuppressWarnings("all")
public class EsbDslLabelProvider extends DefaultEObjectLabelProvider {
  @Inject
  public EsbDslLabelProvider(final AdapterFactoryLabelProvider delegate) {
    super(delegate);
  }
}
