/**
 * generated by Xtext 2.9.0
 */
package com.wso2.esb.dsl.esbDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Command</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.wso2.esb.dsl.esbDsl.Command#getName <em>Name</em>}</li>
 *   <li>{@link com.wso2.esb.dsl.esbDsl.Command#getConfigs <em>Configs</em>}</li>
 * </ul>
 *
 * @see com.wso2.esb.dsl.esbDsl.EsbDslPackage#getCommand()
 * @model
 * @generated
 */
public interface Command extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see com.wso2.esb.dsl.esbDsl.EsbDslPackage#getCommand_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link com.wso2.esb.dsl.esbDsl.Command#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Configs</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Configs</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Configs</em>' attribute.
   * @see #setConfigs(String)
   * @see com.wso2.esb.dsl.esbDsl.EsbDslPackage#getCommand_Configs()
   * @model
   * @generated
   */
  String getConfigs();

  /**
   * Sets the value of the '{@link com.wso2.esb.dsl.esbDsl.Command#getConfigs <em>Configs</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Configs</em>' attribute.
   * @see #getConfigs()
   * @generated
   */
  void setConfigs(String value);

} // Command
