/**
 * generated by Xtext 2.9.0
 */
package com.wso2.esb.dsl.esbDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see com.wso2.esb.dsl.esbDsl.EsbDslFactory
 * @model kind="package"
 * @generated
 */
public interface EsbDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "esbDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.wso2.com/esb/dsl/EsbDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "esbDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  EsbDslPackage eINSTANCE = com.wso2.esb.dsl.esbDsl.impl.EsbDslPackageImpl.init();

  /**
   * The meta object id for the '{@link com.wso2.esb.dsl.esbDsl.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.wso2.esb.dsl.esbDsl.impl.ModelImpl
   * @see com.wso2.esb.dsl.esbDsl.impl.EsbDslPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Participants</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__PARTICIPANTS = 0;

  /**
   * The feature id for the '<em><b>Statements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__STATEMENTS = 1;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link com.wso2.esb.dsl.esbDsl.impl.StatementImpl <em>Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.wso2.esb.dsl.esbDsl.impl.StatementImpl
   * @see com.wso2.esb.dsl.esbDsl.impl.EsbDslPackageImpl#getStatement()
   * @generated
   */
  int STATEMENT = 1;

  /**
   * The number of structural features of the '<em>Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link com.wso2.esb.dsl.esbDsl.impl.ProcessingStatementImpl <em>Processing Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.wso2.esb.dsl.esbDsl.impl.ProcessingStatementImpl
   * @see com.wso2.esb.dsl.esbDsl.impl.EsbDslPackageImpl#getProcessingStatement()
   * @generated
   */
  int PROCESSING_STATEMENT = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROCESSING_STATEMENT__NAME = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Configs</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROCESSING_STATEMENT__CONFIGS = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Processing Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROCESSING_STATEMENT_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link com.wso2.esb.dsl.esbDsl.impl.RoutingStatementImpl <em>Routing Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.wso2.esb.dsl.esbDsl.impl.RoutingStatementImpl
   * @see com.wso2.esb.dsl.esbDsl.impl.EsbDslPackageImpl#getRoutingStatement()
   * @generated
   */
  int ROUTING_STATEMENT = 3;

  /**
   * The feature id for the '<em><b>Source</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROUTING_STATEMENT__SOURCE = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Target</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROUTING_STATEMENT__TARGET = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Action</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROUTING_STATEMENT__ACTION = STATEMENT_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Routing Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROUTING_STATEMENT_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link com.wso2.esb.dsl.esbDsl.impl.ParallelStatementImpl <em>Parallel Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.wso2.esb.dsl.esbDsl.impl.ParallelStatementImpl
   * @see com.wso2.esb.dsl.esbDsl.impl.EsbDslPackageImpl#getParallelStatement()
   * @generated
   */
  int PARALLEL_STATEMENT = 4;

  /**
   * The feature id for the '<em><b>Statements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARALLEL_STATEMENT__STATEMENTS = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Parallel Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARALLEL_STATEMENT_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link com.wso2.esb.dsl.esbDsl.impl.IfStatementImpl <em>If Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.wso2.esb.dsl.esbDsl.impl.IfStatementImpl
   * @see com.wso2.esb.dsl.esbDsl.impl.EsbDslPackageImpl#getIfStatement()
   * @generated
   */
  int IF_STATEMENT = 5;

  /**
   * The feature id for the '<em><b>Expression</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF_STATEMENT__EXPRESSION = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>If Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF_STATEMENT_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link com.wso2.esb.dsl.esbDsl.impl.LoopStatementImpl <em>Loop Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.wso2.esb.dsl.esbDsl.impl.LoopStatementImpl
   * @see com.wso2.esb.dsl.esbDsl.impl.EsbDslPackageImpl#getLoopStatement()
   * @generated
   */
  int LOOP_STATEMENT = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOOP_STATEMENT__NAME = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Loop Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOOP_STATEMENT_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link com.wso2.esb.dsl.esbDsl.impl.GroupStatementImpl <em>Group Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.wso2.esb.dsl.esbDsl.impl.GroupStatementImpl
   * @see com.wso2.esb.dsl.esbDsl.impl.EsbDslPackageImpl#getGroupStatement()
   * @generated
   */
  int GROUP_STATEMENT = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GROUP_STATEMENT__NAME = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Group Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GROUP_STATEMENT_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link com.wso2.esb.dsl.esbDsl.impl.RefStatementImpl <em>Ref Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.wso2.esb.dsl.esbDsl.impl.RefStatementImpl
   * @see com.wso2.esb.dsl.esbDsl.impl.EsbDslPackageImpl#getRefStatement()
   * @generated
   */
  int REF_STATEMENT = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REF_STATEMENT__NAME = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Ref Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REF_STATEMENT_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link com.wso2.esb.dsl.esbDsl.impl.ParticipantStatementImpl <em>Participant Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.wso2.esb.dsl.esbDsl.impl.ParticipantStatementImpl
   * @see com.wso2.esb.dsl.esbDsl.impl.EsbDslPackageImpl#getParticipantStatement()
   * @generated
   */
  int PARTICIPANT_STATEMENT = 9;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARTICIPANT_STATEMENT__NAME = 0;

  /**
   * The feature id for the '<em><b>Participant Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARTICIPANT_STATEMENT__PARTICIPANT_TYPE = 1;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARTICIPANT_STATEMENT__DESCRIPTION = 2;

  /**
   * The number of structural features of the '<em>Participant Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARTICIPANT_STATEMENT_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link com.wso2.esb.dsl.esbDsl.ParticipantType <em>Participant Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.wso2.esb.dsl.esbDsl.ParticipantType
   * @see com.wso2.esb.dsl.esbDsl.impl.EsbDslPackageImpl#getParticipantType()
   * @generated
   */
  int PARTICIPANT_TYPE = 10;


  /**
   * Returns the meta object for class '{@link com.wso2.esb.dsl.esbDsl.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see com.wso2.esb.dsl.esbDsl.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link com.wso2.esb.dsl.esbDsl.Model#getParticipants <em>Participants</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Participants</em>'.
   * @see com.wso2.esb.dsl.esbDsl.Model#getParticipants()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Participants();

  /**
   * Returns the meta object for the containment reference list '{@link com.wso2.esb.dsl.esbDsl.Model#getStatements <em>Statements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Statements</em>'.
   * @see com.wso2.esb.dsl.esbDsl.Model#getStatements()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Statements();

  /**
   * Returns the meta object for class '{@link com.wso2.esb.dsl.esbDsl.Statement <em>Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Statement</em>'.
   * @see com.wso2.esb.dsl.esbDsl.Statement
   * @generated
   */
  EClass getStatement();

  /**
   * Returns the meta object for class '{@link com.wso2.esb.dsl.esbDsl.ProcessingStatement <em>Processing Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Processing Statement</em>'.
   * @see com.wso2.esb.dsl.esbDsl.ProcessingStatement
   * @generated
   */
  EClass getProcessingStatement();

  /**
   * Returns the meta object for the attribute '{@link com.wso2.esb.dsl.esbDsl.ProcessingStatement#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.wso2.esb.dsl.esbDsl.ProcessingStatement#getName()
   * @see #getProcessingStatement()
   * @generated
   */
  EAttribute getProcessingStatement_Name();

  /**
   * Returns the meta object for the attribute '{@link com.wso2.esb.dsl.esbDsl.ProcessingStatement#getConfigs <em>Configs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Configs</em>'.
   * @see com.wso2.esb.dsl.esbDsl.ProcessingStatement#getConfigs()
   * @see #getProcessingStatement()
   * @generated
   */
  EAttribute getProcessingStatement_Configs();

  /**
   * Returns the meta object for class '{@link com.wso2.esb.dsl.esbDsl.RoutingStatement <em>Routing Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Routing Statement</em>'.
   * @see com.wso2.esb.dsl.esbDsl.RoutingStatement
   * @generated
   */
  EClass getRoutingStatement();

  /**
   * Returns the meta object for the attribute '{@link com.wso2.esb.dsl.esbDsl.RoutingStatement#getSource <em>Source</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Source</em>'.
   * @see com.wso2.esb.dsl.esbDsl.RoutingStatement#getSource()
   * @see #getRoutingStatement()
   * @generated
   */
  EAttribute getRoutingStatement_Source();

  /**
   * Returns the meta object for the attribute '{@link com.wso2.esb.dsl.esbDsl.RoutingStatement#getTarget <em>Target</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Target</em>'.
   * @see com.wso2.esb.dsl.esbDsl.RoutingStatement#getTarget()
   * @see #getRoutingStatement()
   * @generated
   */
  EAttribute getRoutingStatement_Target();

  /**
   * Returns the meta object for the attribute '{@link com.wso2.esb.dsl.esbDsl.RoutingStatement#getAction <em>Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Action</em>'.
   * @see com.wso2.esb.dsl.esbDsl.RoutingStatement#getAction()
   * @see #getRoutingStatement()
   * @generated
   */
  EAttribute getRoutingStatement_Action();

  /**
   * Returns the meta object for class '{@link com.wso2.esb.dsl.esbDsl.ParallelStatement <em>Parallel Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Parallel Statement</em>'.
   * @see com.wso2.esb.dsl.esbDsl.ParallelStatement
   * @generated
   */
  EClass getParallelStatement();

  /**
   * Returns the meta object for the containment reference list '{@link com.wso2.esb.dsl.esbDsl.ParallelStatement#getStatements <em>Statements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Statements</em>'.
   * @see com.wso2.esb.dsl.esbDsl.ParallelStatement#getStatements()
   * @see #getParallelStatement()
   * @generated
   */
  EReference getParallelStatement_Statements();

  /**
   * Returns the meta object for class '{@link com.wso2.esb.dsl.esbDsl.IfStatement <em>If Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>If Statement</em>'.
   * @see com.wso2.esb.dsl.esbDsl.IfStatement
   * @generated
   */
  EClass getIfStatement();

  /**
   * Returns the meta object for the attribute '{@link com.wso2.esb.dsl.esbDsl.IfStatement#getExpression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Expression</em>'.
   * @see com.wso2.esb.dsl.esbDsl.IfStatement#getExpression()
   * @see #getIfStatement()
   * @generated
   */
  EAttribute getIfStatement_Expression();

  /**
   * Returns the meta object for class '{@link com.wso2.esb.dsl.esbDsl.LoopStatement <em>Loop Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Loop Statement</em>'.
   * @see com.wso2.esb.dsl.esbDsl.LoopStatement
   * @generated
   */
  EClass getLoopStatement();

  /**
   * Returns the meta object for the attribute '{@link com.wso2.esb.dsl.esbDsl.LoopStatement#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.wso2.esb.dsl.esbDsl.LoopStatement#getName()
   * @see #getLoopStatement()
   * @generated
   */
  EAttribute getLoopStatement_Name();

  /**
   * Returns the meta object for class '{@link com.wso2.esb.dsl.esbDsl.GroupStatement <em>Group Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Group Statement</em>'.
   * @see com.wso2.esb.dsl.esbDsl.GroupStatement
   * @generated
   */
  EClass getGroupStatement();

  /**
   * Returns the meta object for the attribute '{@link com.wso2.esb.dsl.esbDsl.GroupStatement#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.wso2.esb.dsl.esbDsl.GroupStatement#getName()
   * @see #getGroupStatement()
   * @generated
   */
  EAttribute getGroupStatement_Name();

  /**
   * Returns the meta object for class '{@link com.wso2.esb.dsl.esbDsl.RefStatement <em>Ref Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Ref Statement</em>'.
   * @see com.wso2.esb.dsl.esbDsl.RefStatement
   * @generated
   */
  EClass getRefStatement();

  /**
   * Returns the meta object for the attribute '{@link com.wso2.esb.dsl.esbDsl.RefStatement#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.wso2.esb.dsl.esbDsl.RefStatement#getName()
   * @see #getRefStatement()
   * @generated
   */
  EAttribute getRefStatement_Name();

  /**
   * Returns the meta object for class '{@link com.wso2.esb.dsl.esbDsl.ParticipantStatement <em>Participant Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Participant Statement</em>'.
   * @see com.wso2.esb.dsl.esbDsl.ParticipantStatement
   * @generated
   */
  EClass getParticipantStatement();

  /**
   * Returns the meta object for the attribute '{@link com.wso2.esb.dsl.esbDsl.ParticipantStatement#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.wso2.esb.dsl.esbDsl.ParticipantStatement#getName()
   * @see #getParticipantStatement()
   * @generated
   */
  EAttribute getParticipantStatement_Name();

  /**
   * Returns the meta object for the attribute '{@link com.wso2.esb.dsl.esbDsl.ParticipantStatement#getParticipantType <em>Participant Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Participant Type</em>'.
   * @see com.wso2.esb.dsl.esbDsl.ParticipantStatement#getParticipantType()
   * @see #getParticipantStatement()
   * @generated
   */
  EAttribute getParticipantStatement_ParticipantType();

  /**
   * Returns the meta object for the attribute '{@link com.wso2.esb.dsl.esbDsl.ParticipantStatement#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Description</em>'.
   * @see com.wso2.esb.dsl.esbDsl.ParticipantStatement#getDescription()
   * @see #getParticipantStatement()
   * @generated
   */
  EAttribute getParticipantStatement_Description();

  /**
   * Returns the meta object for enum '{@link com.wso2.esb.dsl.esbDsl.ParticipantType <em>Participant Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Participant Type</em>'.
   * @see com.wso2.esb.dsl.esbDsl.ParticipantType
   * @generated
   */
  EEnum getParticipantType();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  EsbDslFactory getEsbDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link com.wso2.esb.dsl.esbDsl.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.wso2.esb.dsl.esbDsl.impl.ModelImpl
     * @see com.wso2.esb.dsl.esbDsl.impl.EsbDslPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Participants</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__PARTICIPANTS = eINSTANCE.getModel_Participants();

    /**
     * The meta object literal for the '<em><b>Statements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__STATEMENTS = eINSTANCE.getModel_Statements();

    /**
     * The meta object literal for the '{@link com.wso2.esb.dsl.esbDsl.impl.StatementImpl <em>Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.wso2.esb.dsl.esbDsl.impl.StatementImpl
     * @see com.wso2.esb.dsl.esbDsl.impl.EsbDslPackageImpl#getStatement()
     * @generated
     */
    EClass STATEMENT = eINSTANCE.getStatement();

    /**
     * The meta object literal for the '{@link com.wso2.esb.dsl.esbDsl.impl.ProcessingStatementImpl <em>Processing Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.wso2.esb.dsl.esbDsl.impl.ProcessingStatementImpl
     * @see com.wso2.esb.dsl.esbDsl.impl.EsbDslPackageImpl#getProcessingStatement()
     * @generated
     */
    EClass PROCESSING_STATEMENT = eINSTANCE.getProcessingStatement();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROCESSING_STATEMENT__NAME = eINSTANCE.getProcessingStatement_Name();

    /**
     * The meta object literal for the '<em><b>Configs</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROCESSING_STATEMENT__CONFIGS = eINSTANCE.getProcessingStatement_Configs();

    /**
     * The meta object literal for the '{@link com.wso2.esb.dsl.esbDsl.impl.RoutingStatementImpl <em>Routing Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.wso2.esb.dsl.esbDsl.impl.RoutingStatementImpl
     * @see com.wso2.esb.dsl.esbDsl.impl.EsbDslPackageImpl#getRoutingStatement()
     * @generated
     */
    EClass ROUTING_STATEMENT = eINSTANCE.getRoutingStatement();

    /**
     * The meta object literal for the '<em><b>Source</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ROUTING_STATEMENT__SOURCE = eINSTANCE.getRoutingStatement_Source();

    /**
     * The meta object literal for the '<em><b>Target</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ROUTING_STATEMENT__TARGET = eINSTANCE.getRoutingStatement_Target();

    /**
     * The meta object literal for the '<em><b>Action</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ROUTING_STATEMENT__ACTION = eINSTANCE.getRoutingStatement_Action();

    /**
     * The meta object literal for the '{@link com.wso2.esb.dsl.esbDsl.impl.ParallelStatementImpl <em>Parallel Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.wso2.esb.dsl.esbDsl.impl.ParallelStatementImpl
     * @see com.wso2.esb.dsl.esbDsl.impl.EsbDslPackageImpl#getParallelStatement()
     * @generated
     */
    EClass PARALLEL_STATEMENT = eINSTANCE.getParallelStatement();

    /**
     * The meta object literal for the '<em><b>Statements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PARALLEL_STATEMENT__STATEMENTS = eINSTANCE.getParallelStatement_Statements();

    /**
     * The meta object literal for the '{@link com.wso2.esb.dsl.esbDsl.impl.IfStatementImpl <em>If Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.wso2.esb.dsl.esbDsl.impl.IfStatementImpl
     * @see com.wso2.esb.dsl.esbDsl.impl.EsbDslPackageImpl#getIfStatement()
     * @generated
     */
    EClass IF_STATEMENT = eINSTANCE.getIfStatement();

    /**
     * The meta object literal for the '<em><b>Expression</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute IF_STATEMENT__EXPRESSION = eINSTANCE.getIfStatement_Expression();

    /**
     * The meta object literal for the '{@link com.wso2.esb.dsl.esbDsl.impl.LoopStatementImpl <em>Loop Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.wso2.esb.dsl.esbDsl.impl.LoopStatementImpl
     * @see com.wso2.esb.dsl.esbDsl.impl.EsbDslPackageImpl#getLoopStatement()
     * @generated
     */
    EClass LOOP_STATEMENT = eINSTANCE.getLoopStatement();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LOOP_STATEMENT__NAME = eINSTANCE.getLoopStatement_Name();

    /**
     * The meta object literal for the '{@link com.wso2.esb.dsl.esbDsl.impl.GroupStatementImpl <em>Group Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.wso2.esb.dsl.esbDsl.impl.GroupStatementImpl
     * @see com.wso2.esb.dsl.esbDsl.impl.EsbDslPackageImpl#getGroupStatement()
     * @generated
     */
    EClass GROUP_STATEMENT = eINSTANCE.getGroupStatement();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GROUP_STATEMENT__NAME = eINSTANCE.getGroupStatement_Name();

    /**
     * The meta object literal for the '{@link com.wso2.esb.dsl.esbDsl.impl.RefStatementImpl <em>Ref Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.wso2.esb.dsl.esbDsl.impl.RefStatementImpl
     * @see com.wso2.esb.dsl.esbDsl.impl.EsbDslPackageImpl#getRefStatement()
     * @generated
     */
    EClass REF_STATEMENT = eINSTANCE.getRefStatement();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute REF_STATEMENT__NAME = eINSTANCE.getRefStatement_Name();

    /**
     * The meta object literal for the '{@link com.wso2.esb.dsl.esbDsl.impl.ParticipantStatementImpl <em>Participant Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.wso2.esb.dsl.esbDsl.impl.ParticipantStatementImpl
     * @see com.wso2.esb.dsl.esbDsl.impl.EsbDslPackageImpl#getParticipantStatement()
     * @generated
     */
    EClass PARTICIPANT_STATEMENT = eINSTANCE.getParticipantStatement();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARTICIPANT_STATEMENT__NAME = eINSTANCE.getParticipantStatement_Name();

    /**
     * The meta object literal for the '<em><b>Participant Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARTICIPANT_STATEMENT__PARTICIPANT_TYPE = eINSTANCE.getParticipantStatement_ParticipantType();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARTICIPANT_STATEMENT__DESCRIPTION = eINSTANCE.getParticipantStatement_Description();

    /**
     * The meta object literal for the '{@link com.wso2.esb.dsl.esbDsl.ParticipantType <em>Participant Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.wso2.esb.dsl.esbDsl.ParticipantType
     * @see com.wso2.esb.dsl.esbDsl.impl.EsbDslPackageImpl#getParticipantType()
     * @generated
     */
    EEnum PARTICIPANT_TYPE = eINSTANCE.getParticipantType();

  }

} //EsbDslPackage
