/**
 * generated by Xtext 2.9.0
 */
package com.wso2.esb.dsl.esbDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Mediator Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.wso2.esb.dsl.esbDsl.MediatorStatement#getMediatorStatement <em>Mediator Statement</em>}</li>
 *   <li>{@link com.wso2.esb.dsl.esbDsl.MediatorStatement#getConfig <em>Config</em>}</li>
 * </ul>
 *
 * @see com.wso2.esb.dsl.esbDsl.EsbDslPackage#getMediatorStatement()
 * @model
 * @generated
 */
public interface MediatorStatement extends Statement
{
  /**
   * Returns the value of the '<em><b>Mediator Statement</b></em>' attribute.
   * The literals are from the enumeration {@link com.wso2.esb.dsl.esbDsl.MediatorType}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Mediator Statement</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Mediator Statement</em>' attribute.
   * @see com.wso2.esb.dsl.esbDsl.MediatorType
   * @see #setMediatorStatement(MediatorType)
   * @see com.wso2.esb.dsl.esbDsl.EsbDslPackage#getMediatorStatement_MediatorStatement()
   * @model
   * @generated
   */
  MediatorType getMediatorStatement();

  /**
   * Sets the value of the '{@link com.wso2.esb.dsl.esbDsl.MediatorStatement#getMediatorStatement <em>Mediator Statement</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Mediator Statement</em>' attribute.
   * @see com.wso2.esb.dsl.esbDsl.MediatorType
   * @see #getMediatorStatement()
   * @generated
   */
  void setMediatorStatement(MediatorType value);

  /**
   * Returns the value of the '<em><b>Config</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Config</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Config</em>' attribute.
   * @see #setConfig(String)
   * @see com.wso2.esb.dsl.esbDsl.EsbDslPackage#getMediatorStatement_Config()
   * @model
   * @generated
   */
  String getConfig();

  /**
   * Sets the value of the '{@link com.wso2.esb.dsl.esbDsl.MediatorStatement#getConfig <em>Config</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Config</em>' attribute.
   * @see #getConfig()
   * @generated
   */
  void setConfig(String value);

} // MediatorStatement
