/**
 * generated by Xtext 2.9.0
 */
package com.wso2.esb.dsl.esbDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Participant Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.wso2.esb.dsl.esbDsl.ParticipantStatement#getName <em>Name</em>}</li>
 *   <li>{@link com.wso2.esb.dsl.esbDsl.ParticipantStatement#getParticipantType <em>Participant Type</em>}</li>
 *   <li>{@link com.wso2.esb.dsl.esbDsl.ParticipantStatement#getDescription <em>Description</em>}</li>
 * </ul>
 *
 * @see com.wso2.esb.dsl.esbDsl.EsbDslPackage#getParticipantStatement()
 * @model
 * @generated
 */
public interface ParticipantStatement extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see com.wso2.esb.dsl.esbDsl.EsbDslPackage#getParticipantStatement_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link com.wso2.esb.dsl.esbDsl.ParticipantStatement#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Participant Type</b></em>' attribute.
   * The literals are from the enumeration {@link com.wso2.esb.dsl.esbDsl.ParticipantType}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Participant Type</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Participant Type</em>' attribute.
   * @see com.wso2.esb.dsl.esbDsl.ParticipantType
   * @see #setParticipantType(ParticipantType)
   * @see com.wso2.esb.dsl.esbDsl.EsbDslPackage#getParticipantStatement_ParticipantType()
   * @model
   * @generated
   */
  ParticipantType getParticipantType();

  /**
   * Sets the value of the '{@link com.wso2.esb.dsl.esbDsl.ParticipantStatement#getParticipantType <em>Participant Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Participant Type</em>' attribute.
   * @see com.wso2.esb.dsl.esbDsl.ParticipantType
   * @see #getParticipantType()
   * @generated
   */
  void setParticipantType(ParticipantType value);

  /**
   * Returns the value of the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Description</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Description</em>' attribute.
   * @see #setDescription(String)
   * @see com.wso2.esb.dsl.esbDsl.EsbDslPackage#getParticipantStatement_Description()
   * @model
   * @generated
   */
  String getDescription();

  /**
   * Sets the value of the '{@link com.wso2.esb.dsl.esbDsl.ParticipantStatement#getDescription <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Description</em>' attribute.
   * @see #getDescription()
   * @generated
   */
  void setDescription(String value);

} // ParticipantStatement
