/*
 * generated by Xtext 2.9.0
 */
package com.wso2.esb.dsl.parser.antlr;

import com.google.inject.Inject;
import com.wso2.esb.dsl.parser.antlr.internal.InternalEsbDslParser;
import com.wso2.esb.dsl.services.EsbDslGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class EsbDslParser extends AbstractAntlrParser {

	@Inject
	private EsbDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalEsbDslParser createParser(XtextTokenStream stream) {
		return new InternalEsbDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public EsbDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(EsbDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
