/**
 * generated by Xtext 2.9.0
 */
package com.wso2.esb.dsl;

import com.wso2.esb.dsl.AbstractEsbDslRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class EsbDslRuntimeModule extends AbstractEsbDslRuntimeModule {
}
