/**
 * generated by Xtext 2.9.0
 */
package com.wso2.esb.dsl;

import com.wso2.esb.dsl.EsbDslStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class EsbDslStandaloneSetup extends EsbDslStandaloneSetupGenerated {
  public static void doSetup() {
    EsbDslStandaloneSetup _esbDslStandaloneSetup = new EsbDslStandaloneSetup();
    _esbDslStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
