/**
 * generated by Xtext 2.9.0
 */
package com.wso2.esb.dsl.esbDsl.impl;

import com.wso2.esb.dsl.esbDsl.EsbDslPackage;
import com.wso2.esb.dsl.esbDsl.Model;
import com.wso2.esb.dsl.esbDsl.ParticipantStatement;
import com.wso2.esb.dsl.esbDsl.Statement;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link com.wso2.esb.dsl.esbDsl.impl.ModelImpl#getIntegrationFlowName <em>Integration Flow Name</em>}</li>
 *   <li>{@link com.wso2.esb.dsl.esbDsl.impl.ModelImpl#getParticipants <em>Participants</em>}</li>
 *   <li>{@link com.wso2.esb.dsl.esbDsl.impl.ModelImpl#getStatements <em>Statements</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ModelImpl extends MinimalEObjectImpl.Container implements Model
{
  /**
   * The default value of the '{@link #getIntegrationFlowName() <em>Integration Flow Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIntegrationFlowName()
   * @generated
   * @ordered
   */
  protected static final String INTEGRATION_FLOW_NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getIntegrationFlowName() <em>Integration Flow Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIntegrationFlowName()
   * @generated
   * @ordered
   */
  protected String integrationFlowName = INTEGRATION_FLOW_NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getParticipants() <em>Participants</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getParticipants()
   * @generated
   * @ordered
   */
  protected EList<ParticipantStatement> participants;

  /**
   * The cached value of the '{@link #getStatements() <em>Statements</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStatements()
   * @generated
   * @ordered
   */
  protected EList<Statement> statements;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ModelImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return EsbDslPackage.Literals.MODEL;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getIntegrationFlowName()
  {
    return integrationFlowName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setIntegrationFlowName(String newIntegrationFlowName)
  {
    String oldIntegrationFlowName = integrationFlowName;
    integrationFlowName = newIntegrationFlowName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EsbDslPackage.MODEL__INTEGRATION_FLOW_NAME, oldIntegrationFlowName, integrationFlowName));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<ParticipantStatement> getParticipants()
  {
    if (participants == null)
    {
      participants = new EObjectContainmentEList<ParticipantStatement>(ParticipantStatement.class, this, EsbDslPackage.MODEL__PARTICIPANTS);
    }
    return participants;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Statement> getStatements()
  {
    if (statements == null)
    {
      statements = new EObjectContainmentEList<Statement>(Statement.class, this, EsbDslPackage.MODEL__STATEMENTS);
    }
    return statements;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case EsbDslPackage.MODEL__PARTICIPANTS:
        return ((InternalEList<?>)getParticipants()).basicRemove(otherEnd, msgs);
      case EsbDslPackage.MODEL__STATEMENTS:
        return ((InternalEList<?>)getStatements()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case EsbDslPackage.MODEL__INTEGRATION_FLOW_NAME:
        return getIntegrationFlowName();
      case EsbDslPackage.MODEL__PARTICIPANTS:
        return getParticipants();
      case EsbDslPackage.MODEL__STATEMENTS:
        return getStatements();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case EsbDslPackage.MODEL__INTEGRATION_FLOW_NAME:
        setIntegrationFlowName((String)newValue);
        return;
      case EsbDslPackage.MODEL__PARTICIPANTS:
        getParticipants().clear();
        getParticipants().addAll((Collection<? extends ParticipantStatement>)newValue);
        return;
      case EsbDslPackage.MODEL__STATEMENTS:
        getStatements().clear();
        getStatements().addAll((Collection<? extends Statement>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case EsbDslPackage.MODEL__INTEGRATION_FLOW_NAME:
        setIntegrationFlowName(INTEGRATION_FLOW_NAME_EDEFAULT);
        return;
      case EsbDslPackage.MODEL__PARTICIPANTS:
        getParticipants().clear();
        return;
      case EsbDslPackage.MODEL__STATEMENTS:
        getStatements().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case EsbDslPackage.MODEL__INTEGRATION_FLOW_NAME:
        return INTEGRATION_FLOW_NAME_EDEFAULT == null ? integrationFlowName != null : !INTEGRATION_FLOW_NAME_EDEFAULT.equals(integrationFlowName);
      case EsbDslPackage.MODEL__PARTICIPANTS:
        return participants != null && !participants.isEmpty();
      case EsbDslPackage.MODEL__STATEMENTS:
        return statements != null && !statements.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (integrationFlowName: ");
    result.append(integrationFlowName);
    result.append(')');
    return result.toString();
  }

} //ModelImpl
